services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        volumes:
            - es_data:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:8.10.2
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - "5601"
        depends_on:
            - elasticsearch
    ###> doctrine/doctrine-bundle ###
    database:
        image: mariadb:10.4.3
        networks:
            - gescom
        environment:
            MYSQL_DATABASE: ${POSTGRES_DB:-ges-abscence}
            # You should definitely change the password in production
            MYSQL_ROOT_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        ports:
            - "3307:3306"
        volumes:
            - orbis_gescom:/var/lib/mysql:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###
    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            PMA_HOST: database
            MYSQL_USER: ${RDS_USER:-root}
            MYSQL_PASSWORD: ${RDS_PASSWORD:-!ChangeMe!}
        ports:
            - "3001:80"
        depends_on:
            - database
        networks:
            - gescom
volumes:
    ###> doctrine/doctrine-bundle ###
    orbis_gescom:
    es_data:
        driver: local

networks:
    gescom:
        driver: bridge
